import type { Notification } from './types';

/**
 * Mock notifications for the admin dashboard.
 * Replace with API-driven data in production.
 */
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    type: 'enrollment',
    title: 'New enrollment',
    message: 'Jane Doe enrolled in the 12-Week Wellness Program.',
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    read: false,
    href: '/admin/enrollments',
  },
  {
    id: '2',
    type: 'client',
    title: 'Client profile updated',
    message: 'John Smith updated their health goals and preferences.',
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
    read: false,
    href: '/admin/clients',
  },
  {
    id: '3',
    type: 'doctor-instruction',
    title: 'New doctor instruction',
    message: 'Dr. Sarah Chen added instructions for client Michael Brown.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    read: true,
    href: '/admin/doctor-instructions',
  },
  {
    id: '4',
    type: 'intake',
    title: 'Intake form submitted',
    message: 'Emily Wilson completed the initial intake assessment.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    read: false,
    href: '/admin/intakes',
  },
  {
    id: '5',
    type: 'program',
    title: 'Program schedule change',
    message: 'Nutrition Library – Categories module was updated.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    read: true,
  },
  {
    id: '6',
    type: 'reminder',
    title: 'Weekly report due',
    message: 'Client progress summary is ready for review.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    read: true,
  },
  {
    id: '7',
    type: 'enrollment',
    title: 'New enrollment',
    message: 'Robert Lee enrolled in the Nutrition Fundamentals program.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
    read: true,
    href: '/admin/enrollments',
  },
  {
    id: '8',
    type: 'client',
    title: 'New client registered',
    message: 'Maria Garcia completed registration and is pending intake.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
    read: false,
    href: '/admin/clients',
  },
  {
    id: '9',
    type: 'system',
    title: 'System maintenance scheduled',
    message:
      'Planned maintenance on Sunday 2am–4am UTC. Brief downtime expected.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120),
    read: true,
  },
  {
    id: '10',
    type: 'intake',
    title: 'Intake form submitted',
    message: 'David Kim submitted the pre-program health questionnaire.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144),
    read: true,
    href: '/admin/intakes',
  },
  {
    id: '11',
    type: 'doctor-instruction',
    title: 'Doctor instruction updated',
    message:
      'Dr. James Wong revised dietary restrictions for client Anna Park.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168),
    read: true,
    href: '/admin/doctor-instructions',
  },
  {
    id: '12',
    type: 'program',
    title: 'New program published',
    message:
      'Movement Library – Stretching module is now available for clients.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 192),
    read: false,
  },
  {
    id: '13',
    type: 'reminder',
    title: 'Follow-up reminder',
    message: '3 clients have pending follow-up assessments this week.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 216),
    read: true,
  },
  {
    id: '14',
    type: 'enrollment',
    title: 'Enrollment completed',
    message: 'Lisa Thompson finished enrollment in the Mindful Eating program.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 240),
    read: true,
    href: '/admin/enrollments',
  },
  {
    id: '15',
    type: 'client',
    title: 'Client milestone',
    message: 'Thomas Wright reached 30-day streak in the wellness program.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 264),
    read: false,
    href: '/admin/clients',
  },
  {
    id: '16',
    type: 'intake',
    title: 'Intake form submitted',
    message: 'Rachel Green completed the initial intake assessment.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 288),
    read: true,
    href: '/admin/intakes',
  },
  {
    id: '17',
    type: 'reminder',
    title: 'Monthly report ready',
    message:
      'February enrollment and retention report is available for download.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 336),
    read: true,
  },
  {
    id: '18',
    type: 'system',
    title: 'Backup completed',
    message: 'Nightly backup completed successfully at 3:00 AM.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 360),
    read: true,
  },
];
