'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangleIcon, ArrowLeftIcon } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import * as React from 'react';
import { toast } from 'sonner';
import { z } from 'zod';

import type { ComboboxOption } from '@/components/shared/form/ComboBoxField';
import ComboboxField from '@/components/shared/form/ComboBoxField';
import FileUploadField, {
  type FileUploadFieldRemoteFile,
} from '@/components/shared/form/FileUploadField';
import RichTextField from '@/components/shared/form/RichTextField';
import TextAreaField from '@/components/shared/form/TextAreaField';
import TextField from '@/components/shared/form/TextField';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { base } from '@/config/api/base';
import { ENDPOINTS } from '@/config/api/endpoints';
import { LOOKUP_ENDPOINTS } from '@/config/api/endpoints/lookup';
import { LANGUAGES } from '@/config/languages';
import { ROUTES } from '@/config/routes';
import { STATUS } from '@/domains/programs/constants';
import { saveProgram } from '@/domains/programs/services';
import type {
  Program as AdminProgram,
  ProgramStructureItem,
  ProgramTranslation,
} from '@/domains/programs/types/admin';
import { http } from '@/lib/api/client';

import StringListField from './StringListField';
import StructureRepeaterField from './StructureRepeaterField';

/** Form row: slug is not edited or sent (generated by API). */
type TranslationData = Omit<ProgramTranslation, 'slug'>;

type GoalLookup = { id: number; name: string; slug: string };

type FieldErrors = Record<string, string>;

/** Thrown after applying `saveRes.errors` to form state so `onError` skips a duplicate toast. */
class ServerFieldValidationError extends Error {
  constructor() {
    super('Validation failed');
    this.name = 'ServerFieldValidationError';
  }
}

function flattenApiErrors(
  raw: Record<string, unknown> | undefined,
): Record<string, string> {
  if (!raw) return {};
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(raw)) {
    if (typeof v === 'string') out[k] = v;
    else if (Array.isArray(v) && v.length > 0) {
      const first = v[0];
      out[k] = typeof first === 'string' ? first : String(first);
    } else if (v != null) out[k] = String(v);
  }
  return out;
}

const LIST_TRANSLATION_FIELDS = new Set([
  'features',
  'ideals',
  'expectations',
  'structures',
]);

/**
 * Maps Laravel validation keys (`translations.0.title`, `goal_ids.0`, …) to wizard `FieldErrors` keys.
 */
function mapProgramApiErrorsToFieldErrors(
  apiErrors: Record<string, string>,
  translationLocalesInPayload: Array<'en' | 'my'>,
): FieldErrors {
  const out: FieldErrors = {};
  const localeAtIndex = (idx: number): 'en' | 'my' | undefined =>
    translationLocalesInPayload[idx];

  for (const [key, msg] of Object.entries(apiErrors)) {
    if (
      key === 'duration' ||
      key === 'price' ||
      key === 'goal_ids' ||
      key === 'status' ||
      key === 'thumbnail'
    ) {
      out[key] = msg;
      continue;
    }
    if (key === 'translations') {
      out['translations.en.title'] =
        out['translations.en.title'] ?? msg;
      continue;
    }
    if (key.startsWith('goal_ids.')) {
      out.goal_ids = out.goal_ids ?? msg;
      continue;
    }

    const transMatch = /^translations\.(\d+)(?:\.(.*))?$/.exec(key);
    if (transMatch) {
      const idx = Number(transMatch[1]);
      const rest = transMatch[2];
      const loc = localeAtIndex(idx);
      if (!loc) continue;
      if (!rest) {
        out[`translations.${loc}.title`] =
          out[`translations.${loc}.title`] ?? msg;
        continue;
      }
      const head = rest.split('.')[0] ?? '';
      if (LIST_TRANSLATION_FIELDS.has(head)) {
        out[`translations.${loc}.${head}`] =
          out[`translations.${loc}.${head}`] ?? msg;
      } else {
        out[`translations.${loc}.${rest}`] = msg;
      }
    }
  }

  return out;
}

const structureRowSchema = z.object({
  period: z.string().min(1, 'Period is required.'),
  title: z.string().min(1, 'Title is required.'),
  description: z.string().min(1, 'Description is required.'),
});

const overviewSchema = z.object({
  duration: z
    .string()
    .min(1, 'Duration is required.')
    .max(10, 'Duration must be at most 10 characters.'),
  price: z.number().int().nonnegative('Price must be zero or greater.'),
});

/** Per-locale content + list/structure rules (used for `en` always, `my` when started). */
const translationContentSchema = z.object({
  title: z.string().min(1, 'Title is required.').max(255),
  tagline: z.string().min(1, 'Tagline is required.').max(255),
  excerpt: z.string().min(1, 'Excerpt is required.'),
  about: z.string().min(1, 'About is required.'),
});

const translationDetailsSchema = z.object({
  features: z.array(z.string()).min(1, 'Add at least one feature.'),
  ideals: z.array(z.string()).min(1, 'Add at least one ideal.'),
  expectations: z.array(z.string()).min(1, 'Add at least one expectation.'),
  structures: z
    .array(structureRowSchema)
    .min(
      1,
      'Add at least one structure block with period, title, and description.',
    ),
});

function mergeTranslationValidationErrors(
  errs: FieldErrors,
  t: TranslationData,
  keyPrefix: 'translations.en' | 'translations.my',
) {
  const content = translationContentSchema.safeParse({
    title: t.title,
    tagline: t.tagline,
    excerpt: t.excerpt,
    about: t.about,
  });
  if (!content.success) {
    for (const issue of content.error.issues) {
      errs[`${keyPrefix}.${String(issue.path[0])}`] = issue.message;
    }
  }

  const details = translationDetailsSchema.safeParse({
    features: t.features,
    ideals: t.ideals,
    expectations: t.expectations,
    structures: normalizeStructureRows(t.structures),
  });
  if (!details.success) {
    let structureMsg: string | undefined;
    for (const issue of details.error.issues) {
      if (issue.path[0] === 'structures') {
        structureMsg = structureMsg ?? issue.message;
      } else {
        errs[`${keyPrefix}.${String(issue.path[0])}`] = issue.message;
      }
    }
    if (structureMsg) errs[`${keyPrefix}.structures`] = structureMsg;
  }
}

function emptyTranslation(locale: 'en' | 'my'): TranslationData {
  return {
    locale,
    title: '',
    tagline: '',
    excerpt: '',
    about: '',
    features: [],
    ideals: [],
    expectations: [],
    structures: [],
  };
}

function normalizeStructureRows(
  rows: ProgramStructureItem[],
): ProgramStructureItem[] {
  return rows
    .map((s) => ({
      period: s.period.trim(),
      title: s.title.trim(),
      description: s.description.trim(),
    }))
    .filter((s) => s.period && s.title && s.description);
}

function isMyTranslationStarted(t: TranslationData): boolean {
  return (
    t.title.trim() !== '' ||
    t.tagline.trim() !== '' ||
    t.excerpt.trim() !== '' ||
    t.about.trim() !== '' ||
    t.features.length > 0 ||
    t.ideals.length > 0 ||
    t.expectations.length > 0 ||
    t.structures.length > 0
  );
}

function mimeFromThumbnailFilename(fileName: string): string {
  const ext = fileName.split('.').pop()?.toLowerCase() ?? '';
  const map: Record<string, string> = {
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    webp: 'image/webp',
    gif: 'image/gif',
    svg: 'image/svg+xml',
  };
  return map[ext] ?? 'image/jpeg';
}

/**
 * Same URL rules as blog posts / program list: relative paths join `base.domainEndpoint`.
 * Sets `mimeType` so `FileUploadField` image previews work (not generic file icons).
 */
function programThumbnailToRemoteFiles(
  raw: string | null | undefined,
): FileUploadFieldRemoteFile[] {
  if (!raw?.trim()) return [];
  const t = raw.trim();
  const fullUrl = t.startsWith('http') ? t : `${base.domainEndpoint}${t}`;
  const lastSegment = fullUrl.split('/').pop() ?? 'thumbnail';
  const fileName = lastSegment.split('?')[0] || 'thumbnail';
  return [
    {
      url: fullUrl,
      name: fileName,
      mimeType: mimeFromThumbnailFilename(fileName),
    },
  ];
}

function resolveSaveStatus(
  isEditMode: boolean,
  current: AdminProgram | undefined,
  publish: boolean,
  catalogVis: boolean,
): 'draft' | 'published' | 'hidden' {
  if (!isEditMode) {
    return publish ? 'published' : 'draft';
  }
  const s = current?.status;
  if (s === STATUS.DRAFT || s === STATUS.ARCHIVED) {
    return publish ? 'published' : 'draft';
  }
  if (s === STATUS.PUBLISHED) {
    return catalogVis ? 'published' : 'hidden';
  }
  if (s === STATUS.HIDDEN) {
    return catalogVis ? 'published' : 'hidden';
  }
  return 'draft';
}

export type ProgramWizardProps = {
  mode: 'create' | 'edit';
  program?: AdminProgram;
  enTranslation?: ProgramTranslation;
  myTranslation?: ProgramTranslation;
};

export default function ProgramWizard({
  mode,
  program,
  enTranslation,
  myTranslation,
}: ProgramWizardProps) {
  const router = useRouter();
  const queryClient = useQueryClient();
  const isEdit = mode === 'edit';

  const [activeLocale, setActiveLocale] = React.useState<'en' | 'my'>('en');
  const [errors, setErrors] = React.useState<FieldErrors>({});

  const [duration, setDuration] = React.useState(program?.duration ?? '');
  const [price, setPrice] = React.useState(program?.price?.amount ?? 0);
  const [goalIds, setGoalIds] = React.useState<number[]>(
    () => program?.goals?.map((g) => Number(g.id)) ?? [],
  );
  const [thumbnailFile, setThumbnailFile] = React.useState<File | null>(null);
  const [existingThumbnail, setExistingThumbnail] = React.useState<
    FileUploadFieldRemoteFile[]
  >(() => programThumbnailToRemoteFiles(program?.thumbnail_url));

  /** Create / draft edit: save and publish to catalog when true. */
  const [publishOnSave, setPublishOnSave] = React.useState(false);
  /** Published / hidden edit: when false, program is hidden from catalog. */
  const [catalogVisible, setCatalogVisible] = React.useState(
    () => program?.status !== STATUS.HIDDEN,
  );

  const [translations, setTranslations] = React.useState<TranslationData[]>(
    () =>
      LANGUAGES.map((lang) => {
        const src = lang.code === 'en' ? enTranslation : myTranslation;
        if (src) {
        return {
          locale: lang.code,
            title: src.title ?? '',
            tagline: src.tagline ?? '',
            excerpt: src.excerpt ?? '',
            about: src.about ?? '',
            features: src.features ?? [],
            ideals: src.ideals ?? [],
            expectations: src.expectations ?? [],
            structures:
              src.structures?.length > 0
                ? src.structures.map((s) => ({ ...s }))
                : [],
          };
        }
        return emptyTranslation(lang.code);
      }),
  );

  const { data: goalsData } = useQuery({
    queryKey: ['lookup', LOOKUP_ENDPOINTS.GOALS],
    queryFn: async () => {
      const res = await http.get<GoalLookup[]>(LOOKUP_ENDPOINTS.GOALS);
      return res.status === 'success' ? res.data : [];
    },
  });

  const goalOptions = React.useMemo<ComboboxOption[]>(
    () =>
      (goalsData ?? []).map((g) => ({
        value: String(g.id),
        label: g.name,
      })),
    [goalsData],
  );

  const updateTranslation = (
    locale: string,
    field: keyof Omit<TranslationData, 'locale'>,
    value: TranslationData[typeof field],
  ) => {
    setTranslations((prev) =>
      prev.map((t) => (t.locale === locale ? { ...t, [field]: value } : t)),
    );
    const key = `translations.${locale}.${field}`;
    setErrors((prev) => {
      if (!(key in prev)) return prev;
      const next = { ...prev };
      delete next[key];
      return next;
    });
  };

  const getTranslationError = (
    locale: string,
    field: keyof Omit<TranslationData, 'locale'>,
  ): string | undefined => errors[`translations.${locale}.${field}`];

  const hasLocaleFieldErrors = (locale: string) =>
    Object.keys(errors).some((k) => k.startsWith(`translations.${locale}.`));

  const showCatalogVisibilitySwitch =
    isEdit &&
    (program?.status === STATUS.PUBLISHED ||
      program?.status === STATUS.HIDDEN);

  const showPublishOnSaveSwitch =
    !isEdit ||
    program?.status === STATUS.DRAFT ||
    program?.status === STATUS.ARCHIVED;

  const mutation = useMutation({
    mutationFn: async () => {
      setErrors({});
        const errs: FieldErrors = {};

      const overviewResult = overviewSchema.safeParse({ duration, price });
      if (!overviewResult.success) {
        for (const issue of overviewResult.error.issues) {
          errs[String(issue.path[0])] = issue.message;
        }
      }
      if (goalIds.length === 0) {
        errs.goal_ids = 'Select at least one goal.';
      }
      if (!thumbnailFile && existingThumbnail.length === 0) {
        errs.thumbnail = 'Thumbnail is required.';
      }

      const en = translations.find((t) => t.locale === 'en')!;
      mergeTranslationValidationErrors(errs, en, 'translations.en');

      const myT = translations.find((t) => t.locale === 'my')!;
      const includesMy = isMyTranslationStarted(myT);
      if (includesMy) {
        mergeTranslationValidationErrors(errs, myT, 'translations.my');
      }

      if (Object.keys(errs).length > 0) {
        setErrors(errs);
        if (Object.keys(errs).some((k) => k.startsWith('translations.en.'))) {
          setActiveLocale('en');
        } else if (
          Object.keys(errs).some((k) => k.startsWith('translations.my.'))
        ) {
          setActiveLocale('my');
        }
        throw new Error('Fix the highlighted fields and try again.');
      }

      const translationPayload = translations
        .filter((t) => t.locale === 'en' || (t.locale === 'my' && includesMy))
        .map((t) => ({
          locale: t.locale,
          title: t.title.trim(),
          tagline: t.tagline.trim(),
          excerpt: t.excerpt.trim(),
          about: t.about.trim(),
          features: t.features.map((s) => s.trim()).filter(Boolean),
          ideals: t.ideals.map((s) => s.trim()).filter(Boolean),
          expectations: t.expectations.map((s) => s.trim()).filter(Boolean),
          structures: normalizeStructureRows(t.structures),
        }));

      const translationLocalesInPayload = translationPayload.map(
        (t) => t.locale,
      );

      const saveBody = {
        ...(isEdit && program?.id != null ? { id: program.id } : {}),
        duration,
        price,
        goal_ids: goalIds,
        translations: translationPayload,
        status: resolveSaveStatus(
          isEdit,
          program,
          publishOnSave,
          catalogVisible,
        ),
      };

      const saveRes = await saveProgram(
        saveBody,
        thumbnailFile,
      );
      if (saveRes.status === 'error') {
        const flat = flattenApiErrors(saveRes.errors);
        const mapped = mapProgramApiErrorsToFieldErrors(
          flat,
          translationLocalesInPayload,
        );
        if (Object.keys(mapped).length > 0) {
          setErrors(mapped);
          if (Object.keys(mapped).some((k) => k.startsWith('translations.en.'))) {
            setActiveLocale('en');
          } else if (
            Object.keys(mapped).some((k) => k.startsWith('translations.my.'))
          ) {
            setActiveLocale('my');
          }
          throw new ServerFieldValidationError();
        }
        throw new Error(saveRes.message ?? 'Failed to save program.');
      }

      return { programId: saveRes.data.id };
    },
    onSuccess: ({ programId }) => {
      queryClient.invalidateQueries({
        queryKey: ['table', ENDPOINTS.ADMIN.MODULES.PROGRAMS.LIST],
      });
      queryClient.invalidateQueries({
        queryKey: ['program-admin-detail', programId],
      });
      queryClient.invalidateQueries({
        queryKey: [ENDPOINTS.ADMIN.MODULES.PROGRAMS.DETAIL(String(programId))],
      });
      toast.success(
        isEdit ? 'Program saved.' : 'Program created.',
      );
      router.push(ROUTES.ADMIN.MODULES.PROGRAMS.LIST);
    },
    onError: (error: Error) => {
      if (error instanceof ServerFieldValidationError) return;
      toast.error(error.message);
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    mutation.mutate();
  };

        return (
    <div className='space-y-6'>
      <form onSubmit={handleSubmit} className='space-y-6' noValidate>
        <section className='border-border max-w-full min-w-0 rounded-md border bg-white p-4 shadow-xs sm:p-5'>
          <div className='flex flex-wrap items-start justify-between gap-4'>
            <div className='min-w-0 space-y-1'>
              <h3 className='text-foreground text-sm font-semibold'>
                Catalog &amp; pricing
              </h3>
              <p className='text-muted-foreground text-[13px] leading-relaxed font-medium'>
                Thumbnail, goals, duration, and pricing apply across every
                language version of this program.
              </p>
            </div>
            <Button
              variant='outline'
              asChild
              className='bg-background hover:bg-muted h-10 w-full gap-1.5 rounded-md border-neutral-300 px-3 text-[13px]! font-semibold sm:w-auto'
            >
              <Link href={ROUTES.ADMIN.MODULES.PROGRAMS.LIST}>
                <ArrowLeftIcon className='size-3.5' />
                Back to programs
              </Link>
            </Button>
          </div>
          <div className='mt-5 space-y-4'>
            <FileUploadField
              label='Thumbnail'
              required
              accept='image/*'
              maxFileSize={5 * 1024 * 1024}
              existingFiles={existingThumbnail}
              onExistingFilesChange={(files) => {
                setExistingThumbnail(files);
                if (files.length === 0) setThumbnailFile(null);
                setErrors((prev) => {
                  const n = { ...prev };
                  delete n.thumbnail;
                  return n;
                });
              }}
              onFilesChange={(files) => {
                setThumbnailFile(files[0] ?? null);
                setErrors((prev) => {
                  const n = { ...prev };
                  delete n.thumbnail;
                  return n;
                });
              }}
              emptyHint='Click or drag image here (max 5 MB)'
              error={errors.thumbnail}
            />

              <div className='grid grid-cols-1 gap-4 sm:grid-cols-2'>
                <TextField
                  label='Duration'
                  required
                placeholder='e.g. 8 weeks'
                  value={duration}
                  onChange={(e) => {
                    setDuration(e.target.value);
                    setErrors((prev) => {
                      const n = { ...prev };
                      delete n.duration;
                      return n;
                    });
                  }}
                  error={errors.duration}
                />
                <TextField
                label='Price'
                  required
                  type='number'
                min={0}
                step={1}
                  placeholder='0'
                value={Number.isNaN(price) ? '' : String(price)}
                  onChange={(e) => {
                  const v = e.target.value;
                  setPrice(v === '' ? 0 : Number.parseInt(v, 10) || 0);
                    setErrors((prev) => {
                      const n = { ...prev };
                      delete n.price;
                      return n;
                    });
                  }}
                  error={errors.price}
                />
            </div>

            <ComboboxField
              label='Goals'
              required
              multiple
              placeholder='Select goals…'
              searchPlaceholder='Search goals…'
              emptyMessage='No goals found.'
              options={goalOptions}
              value={goalIds.map((id) => String(id))}
              onChange={(vals) => {
                setGoalIds((vals ?? []).map((v) => Number(v)));
                setErrors((prev) => {
                  const n = { ...prev };
                  delete n.goal_ids;
                  return n;
                });
              }}
              error={errors.goal_ids}
            />
          </div>
        </section>

        <section className='border-border max-w-full min-w-0 rounded-md border bg-white p-4 shadow-xs sm:p-5'>
          <h3 className='text-foreground text-sm font-semibold'>Visibility</h3>
          <p className='text-muted-foreground mt-1 text-[13px] leading-relaxed font-medium'>
            {showCatalogVisibilitySwitch
              ? 'Published programs can be hidden from the catalog without deleting them.'
              : 'Drafts stay internal until you publish. Thumbnail, goals, duration, and price are required to save.'}
          </p>
          {errors.status ? (
            <p className='text-destructive mt-2 text-sm font-medium'>
              {errors.status}
            </p>
          ) : null}
          <div className='mt-5 space-y-4'>
            {showPublishOnSaveSwitch ? (
              <div className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'>
                <div className='min-w-0 space-y-1'>
                  <Label
                    htmlFor='program-publish-on-save'
                    className='text-foreground text-sm font-semibold'
                  >
                    Publish to catalog
                  </Label>
                  <p className='text-muted-foreground text-xs leading-relaxed font-medium'>
                    When on, the program is published after save (if validation
                    passes). When off, it remains a draft.
                  </p>
                </div>
                <Switch
                  id='program-publish-on-save'
                  className='shrink-0'
                  checked={publishOnSave}
                  onCheckedChange={(v) => {
                    setPublishOnSave(v);
                    setErrors((prev) => {
                      if (!('status' in prev)) return prev;
                      const n = { ...prev };
                      delete n.status;
                      return n;
                    });
                  }}
                />
              </div>
            ) : null}

            {showCatalogVisibilitySwitch ? (
              <div className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'>
                <div className='min-w-0 space-y-1'>
                  <Label
                    htmlFor='program-catalog-visible'
                    className='text-foreground text-sm font-semibold'
                  >
                    Visible in catalog
                  </Label>
                  <p className='text-muted-foreground text-xs leading-relaxed font-medium'>
                    Turn off to hide this program from public listings while
                    keeping data for reactivation.
                  </p>
                </div>
                <Switch
                  id='program-catalog-visible'
                  className='shrink-0'
                  checked={catalogVisible}
                  onCheckedChange={(v) => {
                    setCatalogVisible(v);
                    setErrors((prev) => {
                      if (!('status' in prev)) return prev;
                      const n = { ...prev };
                      delete n.status;
                      return n;
                    });
                  }}
                />
              </div>
            ) : null}
          </div>
        </section>

        <section className='border-border max-w-full min-w-0 rounded-md border bg-white p-4 shadow-xs sm:p-5'>
          <div className='space-y-6'>
            <div>
              <h3 className='text-foreground text-sm font-semibold'>Content</h3>
              <p className='text-muted-foreground mt-1 text-[13px] leading-relaxed font-medium'>
                Titles, lists, and structure blocks are translated per language.
              </p>

              <div className='mt-5'>
                <Tabs
                  value={activeLocale}
                  onValueChange={(v) => setActiveLocale(v as 'en' | 'my')}
                >
                  <TabsList
                    variant='line'
                    className='mb-4 w-full bg-muted! border border-border'
                  >
                  <TabsTrigger
                      value='en'
                      className='relative flex-1 cursor-pointer gap-1.5 text-[13px] font-semibold'
                    >
                      English
                      {hasLocaleFieldErrors('en') ? (
                        <span
                          className='bg-destructive size-1.5 shrink-0 rounded-full'
                          aria-hidden
                        />
                      ) : null}
                  </TabsTrigger>
                    <TabsTrigger
                      value='my'
                      className='relative flex-1 cursor-pointer gap-1.5 text-[13px] font-semibold'
                    >
                      Myanmar
                      {hasLocaleFieldErrors('my') ? (
                        <span
                          className='bg-destructive size-1.5 shrink-0 rounded-full'
                          aria-hidden
                        />
                      ) : null}
                    </TabsTrigger>
            </TabsList>

            {LANGUAGES.map((lang) => {
                    const t = translations.find(
                      (tr) => tr.locale === lang.code,
                    )!;
              return (
                <TabsContent
                  key={lang.code}
                  value={lang.code}
                        className='space-y-4'
                >
                        {lang.code === 'my' && !isMyTranslationStarted(t) ? (
                    <div className='flex items-start gap-2.5 rounded-lg border border-amber-200 bg-amber-50 px-3.5 py-3 text-xs text-amber-800 dark:border-amber-800/50 dark:bg-amber-950/30 dark:text-amber-400'>
                      <AlertTriangleIcon className='mt-0.5 size-3.5 shrink-0' />
                      <span>
                              Myanmar is optional until you start filling
                              it—then all fields and lists must be complete.
                      </span>
                    </div>
                        ) : null}

                  <TextField
                    label='Title'
                    required={lang.code === 'en'}
                    placeholder={
                      lang.code === 'en'
                        ? 'e.g. Weight Loss & Wellness'
                              : 'ခေါင်းစဉ်…'
                    }
                          value={t.title}
                    onChange={(e) =>
                            updateTranslation(
                              lang.code,
                              'title',
                              e.target.value,
                            )
                    }
                    error={getTranslationError(lang.code, 'title')}
                  />
                  <TextField
                    label='Tagline'
                    required={lang.code === 'en'}
                          placeholder='Short phrase for cards'
                          value={t.tagline}
                    onChange={(e) =>
                            updateTranslation(
                              lang.code,
                              'tagline',
                              e.target.value,
                            )
                    }
                    error={getTranslationError(lang.code, 'tagline')}
                  />
                  <TextAreaField
                    label='Excerpt'
                    required={lang.code === 'en'}
                          placeholder='Summary for listings'
                    rows={4}
                          value={t.excerpt}
                    onChange={(e) =>
                            updateTranslation(
                              lang.code,
                              'excerpt',
                              e.target.value,
                            )
                    }
                    error={getTranslationError(lang.code, 'excerpt')}
                  />
                  <RichTextField
                    label='About'
                    required={lang.code === 'en'}
                          value={t.about}
                    onChange={(val) =>
                      updateTranslation(lang.code, 'about', val)
                    }
                    error={getTranslationError(lang.code, 'about')}
                  />

                        <div className='border-border space-y-4 border-t pt-6'>
                          <div>
                            <p className='text-foreground text-sm font-semibold'>
                              Lists &amp; program structure
                            </p>
                            <p className='text-muted-foreground mt-1 text-xs leading-relaxed font-medium'>
                              {lang.code === 'en'
                                ? 'Bullet lists and phased structure for this language.'
                                : 'ဤဘာသာစကားအတွက် စာရင်းများနှင့် အဆင့်ဆင့် ဖွဲ့စည်းပုံ။'}
                            </p>
                          </div>
                          <div className='grid grid-cols-1 gap-4 lg:grid-cols-2 lg:items-start'>
                    <StringListField
                              label='Features'
                      description={
                        lang.code === 'en'
                          ? 'What this program offers.'
                                  : 'ဤပရိုဂရမ်က ပေးသမျှ။'
                      }
                              value={t.features}
                      onChange={(val) =>
                        updateTranslation(lang.code, 'features', val)
                      }
                              error={getTranslationError(
                                lang.code,
                                'features',
                              )}
                    />
                    <StringListField
                              label='Ideals'
                      description={
                        lang.code === 'en'
                          ? 'Who this program is ideal for.'
                                  : 'ဤပရိုဂရမ်သည် ဘယ်သူ့အတွက် သင့်တော်သည်။'
                      }
                              value={t.ideals}
                      onChange={(val) =>
                        updateTranslation(lang.code, 'ideals', val)
                      }
                      error={getTranslationError(lang.code, 'ideals')}
                    />
                          </div>
                    <StringListField
                            label='Expectations'
                      description={
                        lang.code === 'en'
                          ? 'What clients can expect.'
                                : 'ဖောက်သည်များ မျှော်လင့်နိုင်သည်များ။'
                      }
                            value={t.expectations}
                      onChange={(val) =>
                              updateTranslation(
                                lang.code,
                                'expectations',
                                val,
                              )
                            }
                            error={getTranslationError(
                              lang.code,
                              'expectations',
                            )}
                          />
                          <StructureRepeaterField
                            label='Program structure'
                      description={
                        lang.code === 'en'
                                ? 'Each block is a phase: period label, title, and description.'
                                : 'အဆင့်တစ်ခုစီ — ကာလ၊ ခေါင်းစဉ်၊ ဖော်ပြချက်။'
                      }
                            value={t.structures}
                      onChange={(val) =>
                        updateTranslation(lang.code, 'structures', val)
                      }
                            error={getTranslationError(
                              lang.code,
                              'structures',
                            )}
                    />
                  </div>
                </TabsContent>
              );
            })}
          </Tabs>
            </div>
          </div>

            <div className='border-border flex flex-nowrap items-center justify-end gap-2 border-t pt-6'>
              <Button
                type='button'
                variant='outline'
                disabled={mutation.isPending}
                className='text-foreground bg-background hover:bg-muted h-10 shrink-0 cursor-pointer gap-1.5 rounded-md border-neutral-300 px-2.5 text-[13px]! font-semibold'
                onClick={() => router.push(ROUTES.ADMIN.MODULES.PROGRAMS.LIST)}
              >
                Cancel
              </Button>
                <Button
                type='submit'
                disabled={mutation.isPending}
                className='h-10 shrink-0 gap-1.5 rounded-md px-2.5 text-[13px]! font-semibold'
              >
                {mutation.isPending ? 'Saving…' : 'Save program'}
                </Button>
            </div>
          </div>
        </section>
      </form>
          </div>
  );
}
