'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { HeartHandshakeIcon, SaveIcon } from 'lucide-react';
import { useRouter } from 'next/navigation';
import * as React from 'react';
import { toast } from 'sonner';
import { z } from 'zod';

import type { ComboboxOption } from '@/components/shared/form/ComboBoxField';
import ComboboxField from '@/components/shared/form/ComboBoxField';
import FileUploadField, {
  type FileUploadFieldRemoteFile,
} from '@/components/shared/form/FileUploadField';
import RichTextField from '@/components/shared/form/RichTextField';
import TextAreaField from '@/components/shared/form/TextAreaField';
import TextField from '@/components/shared/form/TextField';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { base } from '@/config/api/base';
import { ENDPOINTS } from '@/config/api/endpoints';
import { LOOKUP_ENDPOINTS } from '@/config/api/endpoints/lookup';
import { LANGUAGES } from '@/config/languages';
import { ROUTES } from '@/config/routes';
import { STATUS } from '@/domains/programs/constants';
import { saveProgram } from '@/domains/programs/services';
import type {
  Program as AdminProgram,
  ProgramExpectationItem,
  ProgramStructureItem,
  ProgramTranslation,
} from '@/domains/programs/types/admin';
import { http } from '@/lib/api/client';

import ExpectationRepeaterField from './ExpectationRepeaterField';
import StringListField from './StringListField';
import StructureRepeaterField from './StructureRepeaterField';

/** Form row: slug is not edited or sent (generated by API). */
type TranslationData = Omit<ProgramTranslation, 'slug'>;

type GoalLookup = { id: number; name: string; slug: string };

type FieldErrors = Record<string, string>;

/** Thrown after applying `saveRes.errors` to form state so `onError` skips a duplicate toast. */
class ServerFieldValidationError extends Error {
  constructor() {
    super('Validation failed');
    this.name = 'ServerFieldValidationError';
  }
}

function flattenApiErrors(
  raw: Record<string, unknown> | undefined,
): Record<string, string> {
  if (!raw) return {};
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(raw)) {
    if (typeof v === 'string') out[k] = v;
    else if (Array.isArray(v) && v.length > 0) {
      const first = v[0];
      out[k] = typeof first === 'string' ? first : String(first);
    } else if (v != null) out[k] = String(v);
  }
  return out;
}

const LIST_TRANSLATION_FIELDS = new Set([
  'features',
  'ideals',
  'expectations',
  'structures',
]);

/**
 * Maps Laravel validation keys (`translations.0.title`, `goal_ids.0`, …) to wizard `FieldErrors` keys.
 */
function mapProgramApiErrorsToFieldErrors(
  apiErrors: Record<string, string>,
  translationLocalesInPayload: Array<'en' | 'my'>,
): FieldErrors {
  const out: FieldErrors = {};
  const localeAtIndex = (idx: number): 'en' | 'my' | undefined =>
    translationLocalesInPayload[idx];

  for (const [key, msg] of Object.entries(apiErrors)) {
    if (
      key === 'duration' ||
      key === 'price' ||
      key === 'goal_ids' ||
      key === 'status' ||
      key === 'thumbnail'
    ) {
      out[key] = msg;
      continue;
    }
    if (key === 'translations') {
      out['translations.en.title'] = out['translations.en.title'] ?? msg;
      continue;
    }
    if (key.startsWith('goal_ids.')) {
      out.goal_ids = out.goal_ids ?? msg;
      continue;
    }

    const transMatch = /^translations\.(\d+)(?:\.(.*))?$/.exec(key);
    if (transMatch) {
      const idx = Number(transMatch[1]);
      const rest = transMatch[2];
      const loc = localeAtIndex(idx);
      if (!loc) continue;
      if (!rest) {
        out[`translations.${loc}.title`] =
          out[`translations.${loc}.title`] ?? msg;
        continue;
      }
      const head = rest.split('.')[0] ?? '';
      if (LIST_TRANSLATION_FIELDS.has(head)) {
        out[`translations.${loc}.${head}`] =
          out[`translations.${loc}.${head}`] ?? msg;
      } else {
        out[`translations.${loc}.${rest}`] = msg;
      }
    }
  }

  return out;
}

const expectationRowSchema = z.object({
  title: z.string().min(1, 'The title field is required.'),
  description: z.string().min(1, 'The description field is required.'),
});

const structureRowSchema = z.object({
  period: z.string().min(1, 'The period field is required.'),
  title: z.string().min(1, 'The title field is required.'),
  description: z.string().min(1, 'The description field is required.'),
});

const overviewSchema = z.object({
  duration: z
    .string()
    .min(1, 'The duration field is required.')
    .max(10, 'The duration field must not be greater than 10 characters.'),
  price: z.number().int().nonnegative('Price must be zero or greater.').optional(),
});

/** Per-locale content + list/structure rules (used for `en` always, `my` when started). */
const translationContentSchema = z.object({
  title: z.string().min(1, 'The title field is required.').max(255),
  tagline: z.string().min(1, 'The tagline field is required.').max(255),
  excerpt: z.string().min(1, 'The excerpt field is required.'),
  about: z.string().min(1, 'The about field is required.'),
});

const translationDetailsSchema = z.object({
  features: z.array(z.string()).min(1, 'The features field is required.'),
  ideals: z.array(z.string()).min(1, 'The ideals field is required.'),
  expectations: z
    .array(expectationRowSchema)
    .min(1, 'The expectations field is required.'),
  structures: z
    .array(structureRowSchema)
    .min(1, 'The structures field is required.'),
});

function mergeTranslationValidationErrors(
  errs: FieldErrors,
  t: TranslationData,
  keyPrefix: 'translations.en' | 'translations.my',
) {
  const content = translationContentSchema.safeParse({
    title: t.title,
    tagline: t.tagline,
    excerpt: t.excerpt,
    about: normalizeRichTextValue(t.about),
  });
  if (!content.success) {
    for (const issue of content.error.issues) {
      errs[`${keyPrefix}.${String(issue.path[0])}`] = issue.message;
    }
  }

  const details = translationDetailsSchema.safeParse({
    features: t.features,
    ideals: t.ideals,
    expectations: t.expectations,
    structures: normalizeStructureRows(t.structures),
  });
  if (!details.success) {
    let structureMsg: string | undefined;
    for (const issue of details.error.issues) {
      if (issue.path[0] === 'structures') {
        structureMsg = structureMsg ?? issue.message;
      } else {
        errs[`${keyPrefix}.${String(issue.path[0])}`] = issue.message;
      }
    }
    if (structureMsg) errs[`${keyPrefix}.structures`] = structureMsg;
  }
}

function emptyTranslation(locale: 'en' | 'my'): TranslationData {
  return {
    locale,
    title: '',
    tagline: '',
    excerpt: '',
    about: '',
    features: [],
    ideals: [],
    expectations: [],
    structures: [],
  };
}

function normalizeStructureRows(
  rows: ProgramStructureItem[],
): ProgramStructureItem[] {
  return rows
    .map((s) => ({
      period: s.period.trim(),
      title: s.title.trim(),
      description: s.description.trim(),
    }))
    .filter((s) => s.period && s.title && s.description);
}

function normalizeExpectationRows(
  rows: ProgramExpectationItem[],
): ProgramExpectationItem[] {
  return rows
    .map((e) => ({
      title: (e.title ?? '').trim(),
      description: (e.description ?? '').trim(),
    }))
    .filter((e) => e.title && e.description);
}

function normalizeRichTextValue(value: string): string {
  const plainText = value
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/gi, ' ')
    .trim();
  return plainText.length === 0 ? '' : value;
}

function mimeFromThumbnailFilename(fileName: string): string {
  const ext = fileName.split('.').pop()?.toLowerCase() ?? '';
  const map: Record<string, string> = {
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    webp: 'image/webp',
    gif: 'image/gif',
    svg: 'image/svg+xml',
  };
  return map[ext] ?? 'image/jpeg';
}

/**
 * Same URL rules as blog posts / program list: relative paths join `base.domainEndpoint`.
 * Sets `mimeType` so `FileUploadField` image previews work (not generic file icons).
 */
function programThumbnailToRemoteFiles(
  raw: string | null | undefined,
): FileUploadFieldRemoteFile[] {
  if (!raw?.trim()) return [];
  const t = raw.trim();
  const fullUrl = t.startsWith('http') ? t : `${base.domainEndpoint}${t}`;
  const lastSegment = fullUrl.split('/').pop() ?? 'thumbnail';
  const fileName = lastSegment.split('?')[0] || 'thumbnail';
  return [
    {
      url: fullUrl,
      name: fileName,
      mimeType: mimeFromThumbnailFilename(fileName),
    },
  ];
}

export type ProgramWizardProps = {
  mode: 'create' | 'edit';
  program?: AdminProgram;
  enTranslation?: ProgramTranslation;
  myTranslation?: ProgramTranslation;
};

function getProgramPriceAmount(
  price: AdminProgram['price'] | undefined,
): number {
  if (typeof price === 'number') return price;
  return price?.amount ?? 0;
}

type ProgramChangeSnapshot = {
  duration: string;
  price: number;
  goalIds: number[];
  status:
    | typeof STATUS.DRAFT
    | typeof STATUS.PUBLISHED
    | typeof STATUS.ARCHIVED;
  translations: Array<{
    locale: 'en' | 'my';
    title: string;
    tagline: string;
    excerpt: string;
    about: string;
    features: string[];
    ideals: string[];
    expectations: ProgramExpectationItem[];
    structures: ProgramStructureItem[];
  }>;
};

function buildProgramChangeSnapshot(input: {
  duration: string;
  price: number;
  goalIds: number[];
  status:
    | typeof STATUS.DRAFT
    | typeof STATUS.PUBLISHED
    | typeof STATUS.ARCHIVED;
  translations: TranslationData[];
}): ProgramChangeSnapshot {
  return {
    duration: input.duration.trim(),
    price: Number.isFinite(input.price) ? input.price : 0,
    goalIds: [...new Set(input.goalIds)].sort((a, b) => a - b),
    status: input.status,
    translations: input.translations
      .filter((t) => t.locale === 'en' || t.locale === 'my')
      .map((t) => ({
        locale: t.locale,
        title: t.title.trim(),
        tagline: t.tagline.trim(),
        excerpt: t.excerpt.trim(),
        about: normalizeRichTextValue(t.about),
        features: t.features.map((s) => s.trim()).filter(Boolean),
        ideals: t.ideals.map((s) => s.trim()).filter(Boolean),
        expectations: normalizeExpectationRows(t.expectations),
        structures: normalizeStructureRows(t.structures),
      }))
      .sort((a, b) => a.locale.localeCompare(b.locale)),
  };
}

export default function ProgramWizard({
  mode,
  program,
  enTranslation,
  myTranslation,
}: ProgramWizardProps) {
  const router = useRouter();
  const queryClient = useQueryClient();
  const isEdit = mode === 'edit';
  const formRef = React.useRef<HTMLFormElement | null>(null);

  const [activeLocale, setActiveLocale] = React.useState<'en' | 'my'>('en');
  const [errors, setErrors] = React.useState<FieldErrors>({});

  const [duration, setDuration] = React.useState(program?.duration ?? '');
  const [price, setPrice] = React.useState(
    getProgramPriceAmount(program?.price),
  );
  const [goalIds, setGoalIds] = React.useState<number[]>(
    () => program?.goals?.map((g) => Number(g.id)) ?? [],
  );
  const [thumbnailFile, setThumbnailFile] = React.useState<File | null>(null);
  const [existingThumbnail, setExistingThumbnail] = React.useState<
    FileUploadFieldRemoteFile[]
  >(() => programThumbnailToRemoteFiles(program?.thumbnail_url));

  const [status, setStatus] = React.useState<
    typeof STATUS.DRAFT | typeof STATUS.PUBLISHED | typeof STATUS.ARCHIVED
  >(() => {
    if (
      program?.status === STATUS.PUBLISHED ||
      program?.status === STATUS.ARCHIVED ||
      program?.status === STATUS.HIDDEN
    ) {
      return program.status === STATUS.HIDDEN
        ? STATUS.ARCHIVED
        : program.status;
    }
    return STATUS.DRAFT;
  });

  const [translations, setTranslations] = React.useState<TranslationData[]>(
    () =>
      LANGUAGES.map((lang) => {
        const src = lang.code === 'en' ? enTranslation : myTranslation;
        if (src) {
          return {
            locale: lang.code,
            title: src.title ?? '',
            tagline: src.tagline ?? '',
            excerpt: src.excerpt ?? '',
            about: src.about ?? '',
            features: src.features ?? [],
            ideals: src.ideals ?? [],
            expectations: src.expectations ?? [],
            structures:
              src.structures?.length > 0
                ? src.structures.map((s) => ({ ...s }))
                : [],
          };
        }
        return emptyTranslation(lang.code);
      }),
  );

  const initialChangeSnapshot = React.useMemo<ProgramChangeSnapshot>(() => {
    if (!isEdit || !program) {
      return buildProgramChangeSnapshot({
        duration: '',
        price: 0,
        goalIds: [],
        status: STATUS.DRAFT,
        translations: [emptyTranslation('en'), emptyTranslation('my')],
      });
    }

    return buildProgramChangeSnapshot({
      duration: program.duration ?? '',
      price: getProgramPriceAmount(program.price),
      goalIds: program.goals?.map((g) => Number(g.id)) ?? [],
      status:
        program.status === STATUS.HIDDEN
          ? STATUS.ARCHIVED
          : program.status === STATUS.PUBLISHED
            ? STATUS.PUBLISHED
            : program.status === STATUS.ARCHIVED
              ? STATUS.ARCHIVED
              : STATUS.DRAFT,
      translations: LANGUAGES.map((lang) => {
        const src = lang.code === 'en' ? enTranslation : myTranslation;
        if (!src) return emptyTranslation(lang.code);
        return {
          locale: lang.code,
          title: src.title ?? '',
          tagline: src.tagline ?? '',
          excerpt: src.excerpt ?? '',
          about: src.about ?? '',
          features: src.features ?? [],
          ideals: src.ideals ?? [],
          expectations: src.expectations ?? [],
          structures:
            src.structures?.length > 0
              ? src.structures.map((s) => ({ ...s }))
              : [],
        };
      }),
    });
  }, [isEdit, program, enTranslation, myTranslation]);

  const { data: goalsData } = useQuery({
    queryKey: ['lookup', LOOKUP_ENDPOINTS.GOALS],
    queryFn: async () => {
      const res = await http.get<GoalLookup[]>(LOOKUP_ENDPOINTS.GOALS);
      return res.status === 'success' ? res.data : [];
    },
  });

  const goalOptions = React.useMemo<ComboboxOption[]>(
    () =>
      (goalsData ?? []).map((g) => ({
        value: String(g.id),
        label: g.name,
      })),
    [goalsData],
  );

  const updateTranslation = (
    locale: string,
    field: keyof Omit<TranslationData, 'locale'>,
    value: TranslationData[typeof field],
  ) => {
    const normalizedValue =
      field === 'about' && typeof value === 'string'
        ? normalizeRichTextValue(value)
        : value;
    setTranslations((prev) =>
      prev.map((t) =>
        t.locale === locale ? { ...t, [field]: normalizedValue } : t,
      ),
    );
    const key = `translations.${locale}.${field}`;
    setErrors((prev) => {
      if (!(key in prev)) return prev;
      const next = { ...prev };
      delete next[key];
      return next;
    });
  };

  const getTranslationError = (
    locale: string,
    field: keyof Omit<TranslationData, 'locale'>,
  ): string | undefined => errors[`translations.${locale}.${field}`];

  const hasLocaleFieldErrors = (locale: string) =>
    Object.keys(errors).some((k) => k.startsWith(`translations.${locale}.`));

  const scrollToFirstInvalidField = React.useCallback(() => {
    const formEl = formRef.current;
    if (!formEl) return;

    requestAnimationFrame(() => {
      const invalidEl = formEl.querySelector<HTMLElement>(
        '[aria-invalid="true"]',
      );

      if (invalidEl) {
        invalidEl.scrollIntoView({
          behavior: 'smooth',
          block: 'center',
          inline: 'nearest',
        });
        if (typeof invalidEl.focus === 'function') {
          invalidEl.focus({ preventScroll: true });
        }
        return;
      }

      // Fallback to form top when no invalid control exposes aria-invalid.
      formEl.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  }, []);

  const mutation = useMutation({
    mutationFn: async () => {
      setErrors({});
      const errs: FieldErrors = {};

      const overviewResult = overviewSchema.safeParse({ duration, price });
      if (!overviewResult.success) {
        for (const issue of overviewResult.error.issues) {
          errs[String(issue.path[0])] = issue.message;
        }
      }
      if (goalIds.length === 0) {
        errs.goal_ids = 'The goals field is required.';
      }
      if (!thumbnailFile && existingThumbnail.length === 0) {
        errs.thumbnail = 'The thumbnail field is required.';
      }

      const en = translations.find((t) => t.locale === 'en')!;
      mergeTranslationValidationErrors(errs, en, 'translations.en');

      const myT = translations.find((t) => t.locale === 'my')!;
      mergeTranslationValidationErrors(errs, myT, 'translations.my');

      if (Object.keys(errs).length > 0) {
        setErrors(errs);
        if (Object.keys(errs).some((k) => k.startsWith('translations.en.'))) {
          setActiveLocale('en');
        } else if (
          Object.keys(errs).some((k) => k.startsWith('translations.my.'))
        ) {
          setActiveLocale('my');
        }
        scrollToFirstInvalidField();
        throw new Error('Fix the highlighted fields and try again.');
      }

      const translationPayload = translations
        .filter((t) => t.locale === 'en' || t.locale === 'my')
        .map((t) => ({
          locale: t.locale,
          title: t.title.trim(),
          tagline: t.tagline.trim(),
          excerpt: t.excerpt.trim(),
          about: normalizeRichTextValue(t.about),
          features: t.features.map((s) => s.trim()).filter(Boolean),
          ideals: t.ideals.map((s) => s.trim()).filter(Boolean),
          expectations: normalizeExpectationRows(t.expectations),
          structures: normalizeStructureRows(t.structures),
        }));

      const translationLocalesInPayload = translationPayload.map(
        (t) => t.locale,
      );

      const saveBody = {
        ...(isEdit && program?.id != null ? { id: program.id } : {}),
        duration,
        price,
        goal_ids: goalIds,
        translations: translationPayload,
        status: status === STATUS.ARCHIVED ? STATUS.HIDDEN : status,
      };

      const saveRes = await saveProgram(saveBody, thumbnailFile);
      if (saveRes.status === 'error') {
        const flat = flattenApiErrors(saveRes.errors);
        const mapped = mapProgramApiErrorsToFieldErrors(
          flat,
          translationLocalesInPayload,
        );
        if (Object.keys(mapped).length > 0) {
          setErrors(mapped);
          if (
            Object.keys(mapped).some((k) => k.startsWith('translations.en.'))
          ) {
            setActiveLocale('en');
          } else if (
            Object.keys(mapped).some((k) => k.startsWith('translations.my.'))
          ) {
            setActiveLocale('my');
          }
          scrollToFirstInvalidField();
          throw new ServerFieldValidationError();
        }
        throw new Error(saveRes.message ?? 'Failed to save program.');
      }

      return { programId: saveRes.data.id };
    },
    onSuccess: ({ programId }) => {
      queryClient.invalidateQueries({
        queryKey: ['table', ENDPOINTS.ADMIN.MODULES.PROGRAMS.LIST],
      });
      queryClient.invalidateQueries({
        queryKey: ['program-admin-detail', programId],
      });
      queryClient.invalidateQueries({
        queryKey: [ENDPOINTS.ADMIN.MODULES.PROGRAMS.DETAIL(String(programId))],
      });
      toast.success(
        isEdit
          ? 'The program has been updated successfully.'
          : 'The program has been created successfully.',
      );
      router.push(ROUTES.ADMIN.MODULES.PROGRAMS.LIST);
    },
    onError: (error: Error) => {
      if (error instanceof ServerFieldValidationError) return;
      toast.error(error.message);
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (isEdit) {
      const currentSnapshot = buildProgramChangeSnapshot({
        duration,
        price,
        goalIds,
        status,
        translations,
      });
      const changedValues =
        JSON.stringify(currentSnapshot) !==
        JSON.stringify(initialChangeSnapshot);
      const thumbnailChanged = thumbnailFile !== null;

      if (!changedValues && !thumbnailChanged) {
        toast.info('There are no changes to save.');
        return;
      }
    }
    mutation.mutate();
  };

  const isArchived = status === STATUS.ARCHIVED;
  const isPublished = status === STATUS.PUBLISHED;

  return (
    <form ref={formRef} onSubmit={handleSubmit} noValidate>
      <div className='grid min-w-0 gap-6 lg:grid-cols-3 lg:items-start'>
        <section className='border-border min-w-0 rounded-md border bg-white p-4 shadow-xs sm:p-5 lg:col-span-2'>
          <div className='space-y-6'>
            <div>
              <h3 className='text-foreground/90 text-sm font-semibold'>
                Program Content
              </h3>
              <p className='text-muted-foreground mt-1 text-[13px] leading-relaxed font-medium'>
                Complete localized content so title, highlights, and structure
                are clear and consistent for each language.
              </p>
            </div>

            <div className='mt-5'>
              <Tabs
                value={activeLocale}
                onValueChange={(v) => setActiveLocale(v as 'en' | 'my')}
              >
                <TabsList
                  variant='line'
                  className='bg-muted! border-border mb-4 w-full border'
                >
                  <TabsTrigger
                    value='en'
                    className='relative flex-1 cursor-pointer gap-1.5 text-[13px] font-semibold'
                  >
                    English
                    {hasLocaleFieldErrors('en') ? (
                      <span
                        className='bg-destructive size-1.5 shrink-0 rounded-full'
                        aria-hidden
                      />
                    ) : null}
                  </TabsTrigger>
                  <TabsTrigger
                    value='my'
                    className='relative flex-1 cursor-pointer gap-1.5 text-[13px] font-semibold'
                  >
                    Myanmar
                    {hasLocaleFieldErrors('my') ? (
                      <span
                        className='bg-destructive size-1.5 shrink-0 rounded-full'
                        aria-hidden
                      />
                    ) : null}
                  </TabsTrigger>
                </TabsList>

                {LANGUAGES.map((lang) => {
                  const t = translations.find((tr) => tr.locale === lang.code)!;
                  return (
                    <TabsContent
                      key={lang.code}
                      value={lang.code}
                      className='space-y-4'
                    >
                      <TextField
                        label='Title'
                        required
                        placeholder={
                          lang.code === 'en'
                            ? 'Enter program title (e.g. Weight Loss & Wellness)'
                            : 'ပရိုဂရမ် ခေါင်းစဉ်ကို ထည့်ပါ (ဥပမာ ကိုယ်အလေးချိန် လျှော့ချခြင်းနှင့် ကျန်းမာခြင်း)'
                        }
                        value={t.title}
                        onChange={(e) =>
                          updateTranslation(lang.code, 'title', e.target.value)
                        }
                        error={getTranslationError(lang.code, 'title')}
                      />
                      <TextField
                        label='Tagline'
                        required
                        placeholder={
                          lang.code === 'en'
                            ? 'Enter program tagline (e.g. Transform Your Life)'
                            : 'ပရိုဂရမ် tagline ကိုထည့်ပါ (ဥပမာ၊ သင့်ဘဝကို ပြောင်းလဲပါ)'
                        }
                        value={t.tagline}
                        onChange={(e) =>
                          updateTranslation(
                            lang.code,
                            'tagline',
                            e.target.value,
                          )
                        }
                        error={getTranslationError(lang.code, 'tagline')}
                      />
                      <TextAreaField
                        label='Excerpt'
                        required
                        placeholder={
                          lang.code === 'en'
                            ? 'Enter a short summary for this program'
                            : 'ဤပရိုဂရမ်အတွက် အတိုချုံးကို ထည့်ပါ'
                        }
                        rows={4}
                        value={t.excerpt}
                        onChange={(e) =>
                          updateTranslation(
                            lang.code,
                            'excerpt',
                            e.target.value,
                          )
                        }
                        error={getTranslationError(lang.code, 'excerpt')}
                      />
                      <RichTextField
                        label='About'
                        required
                        placeholder={
                          lang.code === 'en'
                            ? 'Enter a detailed description for this program'
                            : 'ဤပရိုဂရမ်အတွက် အကြောင်းအရာအပြည့်အစုံကို ထည့်သွင်းပါ'
                        }
                        value={t.about}
                        onChange={(val) =>
                          updateTranslation(lang.code, 'about', val)
                        }
                        error={getTranslationError(lang.code, 'about')}
                      />

                      <div className='border-border space-y-4 border-t pt-6'>
                        <div>
                          <h3 className='text-foreground/90 text-sm font-semibold'>
                            Lists and Program Structure
                          </h3>
                          <p className='text-muted-foreground mt-1 text-[13px] leading-relaxed font-medium'>
                            Define feature lists, ideal audience, expectations,
                            and the multi-phase structure for this program.
                          </p>
                        </div>
                        <StringListField
                          label='Key Features'
                          description='List the core features and benefits participants will receive from this program.'
                          value={t.features}
                          placeholder={
                            lang.code === 'en'
                              ? 'Enter a key feature for this program'
                              : 'ပရိုဂရမ်အတွက် သော့ချက်အင်္ဂါရပ်ကို ထည့်သွင်းပါ'
                          }
                          onChange={(val) =>
                            updateTranslation(lang.code, 'features', val)
                          }
                          error={getTranslationError(lang.code, 'features')}
                        />
                        <StringListField
                          label='Ideal Participants'
                          description='Specify the target audience who would benefit the most from this program.'
                          value={t.ideals}
                          placeholder={
                            lang.code === 'en'
                              ? 'Enter an ideal audience for this program'
                              : 'ဤပရိုဂရမ်အတွက် သင့်လျော်သောပါဝင်သူများကို ထည့်သွင်းပါ'
                          }
                          onChange={(val) =>
                            updateTranslation(lang.code, 'ideals', val)
                          }
                          error={getTranslationError(lang.code, 'ideals')}
                        />
                        <ExpectationRepeaterField
                          label='Participant Expectations'
                          description='Outline what participants should anticipate from this program, including commitments, deliverables, and overall experience.'
                          value={t.expectations}
                          locale={lang.code}
                          onChange={(val) =>
                            updateTranslation(lang.code, 'expectations', val)
                          }
                          error={getTranslationError(lang.code, 'expectations')}
                        />
                        <StructureRepeaterField
                          label='Program Structure'
                          description='Define each program phase. For each phase, specify a period label, a title, and a descriptive summary to clearly outline the participant journey.'
                          value={t.structures}
                          locale={lang.code}
                          onChange={(val) =>
                            updateTranslation(lang.code, 'structures', val)
                          }
                          error={getTranslationError(lang.code, 'structures')}
                        />
                      </div>
                    </TabsContent>
                  );
                })}
              </Tabs>
            </div>

            <div className='border-border flex flex-nowrap items-center justify-end gap-2 border-t pt-5'>
              <Button
                type='button'
                variant='outline'
                disabled={mutation.isPending}
                className='text-foreground bg-background hover:bg-muted h-10 shrink-0 cursor-pointer gap-1.5 rounded-md border-neutral-300 px-3 text-[13px]! font-semibold'
                onClick={() => router.push(ROUTES.ADMIN.MODULES.PROGRAMS.LIST)}
              >
                Cancel
              </Button>
              <Button
                type='submit'
                disabled={mutation.isPending}
                className='h-10 shrink-0 gap-1.5 rounded-md px-3 text-[13px]! font-semibold'
              >
                {isEdit ? (
                  <SaveIcon className='size-3.5' />
                ) : (
                  <HeartHandshakeIcon className='size-3.5' />
                )}
                {mutation.isPending
                  ? 'Saving…'
                  : isEdit
                    ? 'Save Changes'
                    : 'Create Care Program'}
              </Button>
            </div>
          </div>
        </section>

        <section className='border-border min-w-0 rounded-md border bg-white p-4 shadow-xs sm:p-5 lg:col-span-1'>
          <div className='space-y-5'>
            <div>
              <h3 className='text-foreground/90 text-sm font-semibold'>
                Program Settings
              </h3>
              <p className='text-muted-foreground mt-1 text-[13px] leading-relaxed font-medium'>
                Configure thumbnail, goals, duration, price, and status before
                saving this program.
              </p>
            </div>

            <div className='border-border space-y-2 border-t pt-4'>
              <FileUploadField
                label='Thumbnail'
                required
                accept='.jpg,.jpeg,.png'
                maxFileSize={5 * 1024 * 1024}
                existingFiles={existingThumbnail}
                onExistingFilesChange={(files) => {
                  setExistingThumbnail(files);
                  if (files.length === 0) setThumbnailFile(null);
                  setErrors((prev) => {
                    const n = { ...prev };
                    delete n.thumbnail;
                    return n;
                  });
                }}
                onFilesChange={(files) => {
                  setThumbnailFile(files[0] ?? null);
                  setErrors((prev) => {
                    const n = { ...prev };
                    delete n.thumbnail;
                    return n;
                  });
                }}
                emptyHint='Browse'
                error={errors.thumbnail}
              />
            </div>

            <div className='border-border grid grid-cols-1 gap-4 border-t pt-4 sm:grid-cols-1'>
              <TextField
                label='Duration'
                required
                placeholder='Enter program duration (e.g. 8 weeks)'
                value={duration}
                onChange={(e) => {
                  setDuration(e.target.value);
                  setErrors((prev) => {
                    const n = { ...prev };
                    delete n.duration;
                    return n;
                  });
                }}
                error={errors.duration}
              />
              <TextField
                label='Price'
                type='number'
                min={0}
                step={1}
                placeholder='0'
                value={Number.isNaN(price) ? '' : String(price)}
                onChange={(e) => {
                  const v = e.target.value;
                  setPrice(v === '' ? 0 : Number.parseInt(v, 10) || 0);
                  setErrors((prev) => {
                    const n = { ...prev };
                    delete n.price;
                    return n;
                  });
                }}
                error={errors.price}
              />
            </div>

            <div className='border-border border-t pt-4'>
              <ComboboxField
                label='Related Goals'
                required
                multiple
                placeholder='Please select related goals'
                searchPlaceholder='Search related goals…'
                emptyMessage='No goals found.'
                options={goalOptions}
                value={goalIds.map((id) => String(id))}
                onChange={(vals) => {
                  setGoalIds((vals ?? []).map((v) => Number(v)));
                  setErrors((prev) => {
                    const n = { ...prev };
                    delete n.goal_ids;
                    return n;
                  });
                }}
                error={errors.goal_ids}
              />
            </div>

            <div className='border-border border-t pt-4'>
              <div className='bg-muted/30 border-border space-y-1 rounded-md border p-3.5'>
                <div className='flex items-center justify-between gap-3'>
                  <Label
                    htmlFor='program-published'
                    className='text-foreground text-[13px] font-semibold'
                  >
                    Publication Status
                  </Label>
                  {isEdit ? (
                    <span className='text-muted-foreground text-[10px] font-bold uppercase'>
                      {isArchived
                        ? 'Archived'
                        : isPublished
                          ? 'Published'
                          : 'Draft'}
                    </span>
                  ) : (
                    <Switch
                      id='program-published'
                      className='h-5 w-9 shrink-0 **:data-[slot=switch-thumb]:size-4 **:data-[slot=switch-thumb]:data-[state=checked]:translate-x-4'
                      checked={isPublished}
                      onCheckedChange={(checked) => {
                        setStatus(checked ? STATUS.PUBLISHED : STATUS.DRAFT);
                        setErrors((prev) => {
                          const n = { ...prev };
                          delete n.status;
                          return n;
                        });
                      }}
                    />
                  )}
                </div>
                <p className='text-muted-foreground text-[12px] leading-relaxed font-medium'>
                  {isPublished
                    ? 'This program is published and visible in catalog listings.'
                    : isArchived
                      ? 'This program is archived and no longer visible in catalog listings.'
                      : 'This program is in draft status and not visible in catalog listings.'}
                </p>
                {isEdit ? (
                  <div className='pt-1'>
                    <Button
                      type='button'
                      variant='outline'
                      disabled={mutation.isPending}
                      className='text-foreground bg-background hover:bg-muted h-9 shrink-0 rounded-md border-neutral-300 px-2.5 text-[13px]! font-semibold'
                      onClick={() => {
                        setStatus(
                          isArchived
                            ? STATUS.PUBLISHED
                            : isPublished
                              ? STATUS.ARCHIVED
                              : STATUS.PUBLISHED,
                        );
                        setErrors((prev) => {
                          const n = { ...prev };
                          delete n.status;
                          return n;
                        });
                      }}
                    >
                      {isArchived
                        ? 'Move to Published'
                        : isPublished
                          ? 'Move to Archived'
                          : 'Move to Published'}
                    </Button>
                  </div>
                ) : null}
              </div>
              {errors.status ? (
                <p className='text-destructive mt-2 text-xs font-medium'>
                  {errors.status}
                </p>
              ) : null}
            </div>
          </div>
        </section>
      </div>
    </form>
  );
}
